### ISSUE TITLE
image wrap style request

### ISSUE THREAD

**Issue by mark-conrad** [mark-conrad/worcester-house#1]
Sometimes I think we need to wrap text around photos. There was a style in the old site that was right_pic or left_pic - could you replicate those so they are neat. Currently they come out like on this page:  https://www.worcesterhouse.org/room-rentals

**Comment by zodus** [comment]
I have restored the css rules as it was before (left/right_pic)
I want to say that I'd be happy to prepare and format articles the correct way if you'd let me. 
As we transition to newer approaches we should at least try to follow guidelines and try new ways of doing things. Otherwise, I'm afraid we will be stuck using the same old ways which, although comfortable, might not render the desired results.
